name: Update README with GitHub Activity

on:
  schedule:
    - cron: '0 */6 * * *'  # هر ۶ ساعت اجرا میشه
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Generate GitHub Activity
        uses: JamesIves/github-activity-readme@v0.4.1
        with:
          COMMIT_MSG: "Update README with latest activity"
          MAX_LINES: 6
